## Cleaning factRuEval-2016

This dataset is somewhat challenging. The tokens, spans, objects (labels), and text are all being kept in separate files...for every single training/test observation. 

To summarize the work that is being done below:

The goal is to get the data into a format where we have tokens on the left and their labels on the right in an easily readable text file. To do this, we need to join the token file to the span file to the object file (because there is insufficient information in the token file to join it to the object file directly).

Steps:

1. Read in the token data.
2. Read in and process the span data.
3. Process the label data, removing duplicates / "recursive" labels.
4. Combine the tokens, spans, and labels.
5. Filter out unwanted label types ("fact" labels vs. NER labels, because fact-finding was a separate task for this dataset)
6. **(To do next)** Use the B-PER and I-PER convention to identify which tokens belong to the same label (for example, "National Bank of Ukraine").

The way a couple of these steps are implemented is likely not ideal for large datasets, but will probably work for now.

In [53]:
import pandas as pd
token_col_names = ['id', 'begin_index', 'length', 'text']
test_obj = pd.read_csv('../data/ru/factRuEval-2016/devset/book_194.tokens', 
                       sep=' ', skip_blank_lines=False, header=None)
test_obj.columns = token_col_names

test_obj[:15]

          id  begin_index  length       text
0   210354.0          0.0     6.0     Россия
1   210355.0          7.0     4.0       дала
2   210356.0         12.0     7.0    Украине
3   210357.0         20.0     6.0     кредит
4   210358.0         27.0     2.0         на
5   210359.0         30.0     5.0      сумму
6   210360.0         36.0     1.0          2
7   210361.0         38.0     9.0  миллиарда
8   210362.0         48.0     8.0   долларов
9   210363.0         56.0     1.0          ,
10  210364.0         58.0     8.0   сообщает
11  210365.0         67.0     8.0   Лента.ру
12  210366.0         75.0     1.0          .
13       NaN          NaN     NaN        NaN
14  210367.0         77.0     6.0     Деньги

In [201]:
test_file = '../data/ru/factRuEval-2016/devset/book_194.spans'

def extract_span_info(filename):
    
    with open(filename) as s:
        info = s.readlines()
    
    intermediate = [l.split() for l in info]
    
    # Extract only the necessary fields for each intermediate representation
    # Grab token ids + phrase text, span id, mention type, position, and length of span/phrase
    fields = [(i_rep[7:], i_rep[0], i_rep[1], i_rep[2], i_rep[5]) 
              for i_rep in intermediate]
    
    return fields

extracted = extract_span_info(test_file)

### Let's try something else. We're going to treat this as a pure, span-only task where we do NOT introduce any token information from the span data, and we rely only on beginning index for joining with tokens. 

#### Sadly, beginning index is NOT available on the token level inside of the span data. Instead, it's only available on the span level, so I'll need to manually calculate somehow.

In [324]:
# later I can just rewrite the fn to exclude the token info
span_df = pd.DataFrame(extracted).iloc[:, 1:]
span_df.columns = ['position_id', 'mention_type', 'begin_index', 'n_tokens']

# Convert dtypes for joining with token df
for col in ['position_id', 'n_tokens', 'begin_index']:
    span_df[col] = span_df[col].astype('int')
    
# Reuse previous work on labels    
get_label = lambda x: label_dict.get(str(x), np.nan)
span_df['label'] = span_df['position_id'].apply(get_label)

span_df

    position_id mention_type  begin_index  n_tokens   label
0         26213     loc_name            0         1  LocOrg
1         26214     loc_name           12         1  LocOrg
2         26215     org_name           67         1     Org
3         26216    org_descr          124         2     Org
4         26217     loc_name          142         1     Org
5         26218    org_descr          137         1     Org
6         38269    org_descr          104         1     Org
7         38270    org_descr           93         2     Org
8         77695      geo_adj           93         1     NaN
9         26219     org_name          226         3     Org
10        26220    org_descr          237         1     Org
11        26221     org_name          237         2     Org
12        26222     org_name          431         1     Org
13        77696      geo_adj          226         1     NaN
14        26223     org_name          609         3     Org
15        26224    org_descr          629         1     Org
16        26225    org_descr          621         2     Org
17        26226     org_name          645         1     Org
18        77697      geo_adj          609         1     NaN

In [367]:
labeled_tokens_df_2 = test_obj.merge(span_df, 
                                    left_on='begin_index',
                                    right_on='begin_index',
                                    how='left')

# Position IDs being associated with multiple mention types created 
# duplicate tokens in the join, so we drop those now
labeled_tokens_df_2.drop_duplicates(subset=['begin_index', 'text'], 
                                    keep='first', inplace=True)

labeled_tokens_df_2['lag(n_tokens)'] = labeled_tokens_df_2['n_tokens'].shift(1)

cond1 = (labeled_tokens_df_2['n_tokens'] == 1) & (labeled_tokens_df_2['lag(n_tokens)'].isna())
labeled_tokens_df_2['label1'] = np.where(cond1, 'B-' + labeled_tokens_df_2['label'], np.nan)

cond2 = (labeled_tokens_df_2['n_tokens'] >= 1) & (labeled_tokens_df_2['lag(n_tokens)'].isna())
labeled_tokens_df_2['label2'] = np.where(cond2, 'B-' + labeled_tokens_df_2['label'], np.nan)

# Label and lag(n_tokens) are both non-null (indicates being inside of a phrase)
cond3 = (labeled_tokens_df_2['label'].notna()) & (labeled_tokens_df_2['lag(n_tokens)'].notna())
labeled_tokens_df_2['label3'] = np.where(cond3, 'I-' + labeled_tokens_df_2['label'], np.nan)

# If label1 is not null, use label 1, etc., if label3 is null, use label 
# (label will be NaN for non-labeled words, which is what we want)
labeled_tokens_df_2['final_label'] = \
    np.where(labeled_tokens_df_2['label1'].notna(), 
             labeled_tokens_df_2['label1'],
             np.where(labeled_tokens_df_2['label2'].notna(), 
                      labeled_tokens_df_2['label2'],
                     np.where(labeled_tokens_df_2['label3'].notna(), 
                              labeled_tokens_df_2['label3'],
                             labeled_tokens_df_2['label'])))

labeled_tokens_df_2.loc[:, 'text':]

# The four possible labels are Org, Location, Person, and LocOrg
# Now: How do I go from this to a series of labels based on whether a token is
# the beginning or inside of the label?

# Outline the possible situations:
# 1. (label1) A single token has a label and the word before it is not labeled
# 2. (label2) A token is labeled and is the first word of a multi-word phrase
# 3. (label3) A token is labeled and is a non-first word of a multi-word phrase
# 4. Others? (I think that due to sufficient separation of tokens--no two NE words 
#    or phrases sitting directly next to each other--this should be correct, but need
#    to verify)

,text,position_id,mention_type,n_tokens,label,lag(n_tokens),label1,label2,label3,final_label
0,Россия,26213.0,loc_name,1.0,LocOrg,NaN,B-LocOrg,B-LocOrg,NaN,B-LocOrg
1,дала,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
2,Украине,26214.0,loc_name,1.0,LocOrg,NaN,B-LocOrg,B-LocOrg,NaN,B-LocOrg
3,кредит,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
4,на,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,сумму,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,миллиарда,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,долларов,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,",",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,сообщает,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Лента.ру,26215.0,org_name,1.0,Org,NaN,B-Org,B-Org,NaN,B-Org
12,.,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Деньги,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,получило,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,украинское,38270.0,org_descr,2.0,Org,NaN,NaN,B-Org,NaN,B-Org
18,правительство,38269.0,org_descr,1.0,Org,2.0,NaN,NaN,I-Org,I-Org
19,через,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
20,Национальный,26216.0,org_descr,2.0,Org,NaN,NaN,B-Org,NaN,B-Org
21,банк,26218.0,org_descr,1.0,Org,2.0,NaN,NaN,I-Org,I-Org
22,Украины,26217.0,loc_name,1.0,Org,1.0,NaN,NaN,I-Org,I-Org
23,",",NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
24,однако,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,кто,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,именно,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,выступил,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,кредитором,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,с,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,российской,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
76,могли,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,поступить,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,от,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,российских,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,банков,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,",",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,а,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,также,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,о,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,том,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,",",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,что,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,кредит,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,мог,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,быть,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,выделен,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,в,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,рамках,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,программы,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,по,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,достройке,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,двух,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,блоков,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,Хмельницкой,26223.0,org_name,3.0,Org,NaN,NaN,B-Org,NaN,B-Org
101,атомной,26225.0,org_descr,2.0,Org,3.0,NaN,NaN,I-Org,I-Org
102,электростанции,26224.0,org_descr,1.0,Org,2.0,NaN,NaN,I-Org,I-Org
103,(,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
104,ХАЭС,26226.0,org_name,1.0,Org,NaN,B-Org,B-Org,NaN,B-Org
105,),NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
106,.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [202]:
def separate_ids_and_text(id_text_list):
    
    if len(id_text_list) == 2:
        return [{id_text_list[0]: id_text_list[1]}]
    
    else:
        list_len = len(id_text_list)
        text_idx = list_len // 2
        return [{item[0]: item[1]} for item 
                in zip(id_text_list[:text_idx], id_text_list[text_idx:])
               ]
    
df = pd.DataFrame(extracted)
df[0] = df[0].apply(separate_ids_and_text)
df = df.explode(0)
df['token_id'] = df[0].apply(lambda x: list(x.keys())[0])
df['text'] = df[0].apply(lambda x: list(x.values())[0])
df.columns = ['0', 'span_id', 'mention_type', 'begin_index', 'span_length', 'token_id', 'text']
df = df[['token_id', 'span_id', 'text', 'span_length', 'begin_index', 'mention_type']]

# Convert dtypes for joining with token df
for col in ['token_id', 'span_length', 'begin_index']:
    df[col] = df[col].astype('int')

In [300]:
df[:10]

,token_id,span_id,text,span_length,begin_index,mention_type,label
0,210354,26213,Россия,1,0,loc_name,LocOrg
1,210356,26214,Украине,1,12,loc_name,LocOrg
2,210365,26215,Лента.ру,1,67,org_name,Org
3,210372,26216,Национальный,2,124,org_descr,Org
3,210373,26216,банк,2,124,org_descr,Org
4,210374,26217,Украины,1,142,loc_name,Org
5,210373,26218,банк,1,137,org_descr,Org
6,210370,38269,правительство,1,104,org_descr,Org
7,210369,38270,украинское,2,93,org_descr,Org
7,210370,38270,правительство,2,93,org_descr,Org

In [283]:
# Read in and process the labels
test_labels = '../data/ru/factRuEval-2016/devset/book_194.objects'

# This is NER, so each label can have one or more token IDs associated with it.
# Each line/list `l` holds the token IDs from index 2 up to the hash symbol.
with open(test_labels) as t:
    labs = [l.split() for l in t.readlines()]
    ids_labs_only = [(l[2: l.index('#')], l[1]) for l in labs]
 
# `seen` keeps track of span_ids we have already added as key-label pairs.
# Some label files have redundant tags (spans have multiple labels),
# so we need to only include the first instance of each span.
# Open book_194.objects for an example of this; span 26217, 'Украины',
# is tagged both as part of an Org AND on its own as LocOrg, even though
# it only occurs once in the sentence.
ind_dicts = []
seen = [] 
for item in ids_labs_only:
    for span_id in item[0]:
        if span_id not in seen:
            ind_dicts.append({span_id: item[1]})
            seen.append(span_id)
        
# Update the first dict with all the other k-v pairs 
for d in ind_dicts:
    ind_dicts[0].update(d)
    
# `label_dict` is now a dict with span_ids as keys and their labels as values.
label_dict = ind_dicts[0]

get_label = lambda x: label_dict.get(x, np.nan)
df['label'] = df['span_id'].apply(get_label)

In [298]:
labeled_tokens_df = test_obj.merge(df, 
                                    left_on=['id', 'begin_index', 'text'], 
                                    right_on=['token_id', 'begin_index', 'text'], 
                                    how='left')

labeled_tokens_df[:20]

# Note to self: span_id may more accurately be called position_id. Rename later

,id,begin_index,length,text,token_id,span_id,span_length,mention_type,label
0,210354.0,0.0,6.0,Россия,210354.0,26213,1.0,loc_name,LocOrg
1,210355.0,7.0,4.0,дала,NaN,NaN,NaN,NaN,NaN
2,210356.0,12.0,7.0,Украине,210356.0,26214,1.0,loc_name,LocOrg
3,210357.0,20.0,6.0,кредит,NaN,NaN,NaN,NaN,NaN
4,210358.0,27.0,2.0,на,NaN,NaN,NaN,NaN,NaN
5,210359.0,30.0,5.0,сумму,NaN,NaN,NaN,NaN,NaN
6,210360.0,36.0,1.0,2,NaN,NaN,NaN,NaN,NaN
7,210361.0,38.0,9.0,миллиарда,NaN,NaN,NaN,NaN,NaN
8,210362.0,48.0,8.0,долларов,NaN,NaN,NaN,NaN,NaN
9,210363.0,56.0,1.0,",",NaN,NaN,NaN,NaN,NaN
10,210364.0,58.0,8.0,сообщает,NaN,NaN,NaN,NaN,NaN
11,210365.0,67.0,8.0,Лента.ру,210365.0,26215,1.0,org_name,Org
12,210366.0,75.0,1.0,.,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,210367.0,77.0,6.0,Деньги,NaN,NaN,NaN,NaN,NaN
15,210368.0,84.0,8.0,получило,NaN,NaN,NaN,NaN,NaN
16,210369.0,93.0,10.0,украинское,210369.0,38270,2.0,org_descr,Org
17,210369.0,93.0,10.0,украинское,210369.0,77695,1.0,geo_adj,NaN
18,210370.0,104.0,13.0,правительство,210370.0,38269,1.0,org_descr,Org
19,210371.0,118.0,5.0,через,NaN,NaN,NaN,NaN,NaN

In [301]:
# `cond` checks if the join was successful, but the text is unlabeled.
# (that is, "token_id NOT NULL, label IS NULL")
# If this is the case, we know it's a duplicate of a previous token,
# and was duplicated in the join with the span + label data (due to the 
# "redundant tags" issue mentioned above), so we can safely drop these.
cond = ~labeled_tokens_df['token_id'].isna() & labeled_tokens_df['label'].isna() 

# Invert the condition to get only the non-duplicate tokens
labeled_tokens_df = labeled_tokens_df[~cond]

# Now we're quite close to having a df of text and labels!
# Next step is to detect if the span length is > 1 and appropriately
# indicate in the label which tokens belong to the same "label"--
# for example "National Bank of Ukraine" should be labeled as a single
# entity. We can use I-PER + B-PER / I-ORG / B-ORG for this, as is 
# usual for NER datasets.
labeled_tokens_df[:13]

,id,begin_index,length,text,token_id,span_id,span_length,mention_type,label
0,210354.0,0.0,6.0,Россия,210354.0,26213,1.0,loc_name,LocOrg
1,210355.0,7.0,4.0,дала,NaN,NaN,NaN,NaN,NaN
2,210356.0,12.0,7.0,Украине,210356.0,26214,1.0,loc_name,LocOrg
3,210357.0,20.0,6.0,кредит,NaN,NaN,NaN,NaN,NaN
4,210358.0,27.0,2.0,на,NaN,NaN,NaN,NaN,NaN
5,210359.0,30.0,5.0,сумму,NaN,NaN,NaN,NaN,NaN
6,210360.0,36.0,1.0,2,NaN,NaN,NaN,NaN,NaN
7,210361.0,38.0,9.0,миллиарда,NaN,NaN,NaN,NaN,NaN
8,210362.0,48.0,8.0,долларов,NaN,NaN,NaN,NaN,NaN
9,210363.0,56.0,1.0,",",NaN,NaN,NaN,NaN,NaN
10,210364.0,58.0,8.0,сообщает,NaN,NaN,NaN,NaN,NaN
11,210365.0,67.0,8.0,Лента.ру,210365.0,26215,1.0,org_name,Org
12,210366.0,75.0,1.0,.,NaN,NaN,NaN,NaN,NaN

In [303]:
# The four possible labels are Org, Location, Person, and LocOrg
labeled_tokens_df[:50]

# Oh no...my filter trick didn't remove all the duplicates. 
# (See indices 39-40.)

,id,begin_index,length,text,token_id,span_id,span_length,mention_type,label
0,210354.0,0.0,6.0,Россия,210354.0,26213,1.0,loc_name,LocOrg
1,210355.0,7.0,4.0,дала,NaN,NaN,NaN,NaN,NaN
2,210356.0,12.0,7.0,Украине,210356.0,26214,1.0,loc_name,LocOrg
3,210357.0,20.0,6.0,кредит,NaN,NaN,NaN,NaN,NaN
4,210358.0,27.0,2.0,на,NaN,NaN,NaN,NaN,NaN
5,210359.0,30.0,5.0,сумму,NaN,NaN,NaN,NaN,NaN
6,210360.0,36.0,1.0,2,NaN,NaN,NaN,NaN,NaN
7,210361.0,38.0,9.0,миллиарда,NaN,NaN,NaN,NaN,NaN
8,210362.0,48.0,8.0,долларов,NaN,NaN,NaN,NaN,NaN
9,210363.0,56.0,1.0,",",NaN,NaN,NaN,NaN,NaN
10,210364.0,58.0,8.0,сообщает,NaN,NaN,NaN,NaN,NaN
11,210365.0,67.0,8.0,Лента.ру,210365.0,26215,1.0,org_name,Org
12,210366.0,75.0,1.0,.,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,210367.0,77.0,6.0,Деньги,NaN,NaN,NaN,NaN,NaN
15,210368.0,84.0,8.0,получило,NaN,NaN,NaN,NaN,NaN
16,210369.0,93.0,10.0,украинское,210369.0,38270,2.0,org_descr,Org
18,210370.0,104.0,13.0,правительство,210370.0,38269,1.0,org_descr,Org
19,210371.0,118.0,5.0,через,NaN,NaN,NaN,NaN,NaN
20,210372.0,124.0,12.0,Национальный,210372.0,26216,2.0,org_descr,Org
21,210373.0,137.0,4.0,банк,210373.0,26218,1.0,org_descr,Org
22,210374.0,142.0,7.0,Украины,210374.0,26217,1.0,loc_name,Org
23,210375.0,149.0,1.0,",",NaN,NaN,NaN,NaN,NaN
24,210376.0,151.0,6.0,однако,NaN,NaN,NaN,NaN,NaN
25,210377.0,158.0,3.0,кто,NaN,NaN,NaN,NaN,NaN
26,210378.0,162.0,6.0,именно,NaN,NaN,NaN,NaN,NaN
27,210379.0,169.0,8.0,выступил,NaN,NaN,NaN,NaN,NaN
28,210380.0,178.0,10.0,кредитором,NaN,NaN,NaN,NaN,NaN
29,210381.0,189.0,1.0,с,NaN,NaN,NaN,NaN,NaN
30,210382.0,191.0,10.0,российской,NaN,NaN,NaN,NaN,NaN
31,210383.0,202.0,7.0,стороны,NaN,NaN,NaN,NaN,NaN
32,210384.0,209.0,1.0,",",NaN,NaN,NaN,NaN,NaN
33,210385.0,211.0,10.0,неизвестно,NaN,NaN,NaN,NaN,NaN
34,210386.0,221.0,1.0,.,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,210387.0,224.0,1.0,В,NaN,NaN,NaN,NaN,NaN
37,210388.0,226.0,10.0,российском,210388.0,26219,3.0,org_name,Org
39,210389.0,237.0,12.0,министерстве,210389.0,26220,1.0,org_descr,Org
40,210389.0,237.0,12.0,министерстве,210389.0,26221,2.0,org_name,Org
41,210390.0,250.0,8.0,финансов,NaN,NaN,NaN,NaN,NaN
42,210391.0,259.0,10.0,утверждают,NaN,NaN,NaN,NaN,NaN
43,210392.0,269.0,1.0,",",NaN,NaN,NaN,NaN,NaN
44,210393.0,271.0,3.0,что,NaN,NaN,NaN,NaN,NaN
45,210394.0,275.0,2.0,на,NaN,NaN,NaN,NaN,NaN
46,210395.0,278.0,15.0,государственном,NaN,NaN,NaN,NaN,NaN
47,210396.0,294.0,6.0,уровне,NaN,NaN,NaN,NaN,NaN
48,210397.0,301.0,6.0,кредит,NaN,NaN,NaN,NaN,NaN
49,210398.0,308.0,2.0,не,NaN,NaN,NaN,NaN,NaN
50,210399.0,311.0,14.0,предоставлялся,NaN,NaN,NaN,NaN,NaN
51,210400.0,325.0,1.0,",",NaN,NaN,NaN,NaN,NaN